// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockQuotaService creates a new instance of MockQuotaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaService {
	mock := &MockQuotaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuotaService is an autogenerated mock type for the QuotaService type
type MockQuotaService struct {
	mock.Mock
}

type MockQuotaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaService) EXPECT() *MockQuotaService_Expecter {
	return &MockQuotaService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockQuotaService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockQuotaService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockQuotaService_Expecter) Config() *MockQuotaService_Config_Call {
	return &MockQuotaService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockQuotaService_Config_Call) Run(run func()) *MockQuotaService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuotaService_Config_Call) Return(manager config.Manager) *MockQuotaService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockQuotaService_Config_Call) RunAndReturn(run func() config.Manager) *MockQuotaService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockQuotaService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockQuotaService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockQuotaService_Expecter) Context() *MockQuotaService_Context_Call {
	return &MockQuotaService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockQuotaService_Context_Call) Run(run func()) *MockQuotaService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuotaService_Context_Call) Return(context core.Context) *MockQuotaService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockQuotaService_Context_Call) RunAndReturn(run func() core.Context) *MockQuotaService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockQuotaService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockQuotaService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockQuotaService_Expecter) DB() *MockQuotaService_DB_Call {
	return &MockQuotaService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockQuotaService_DB_Call) Run(run func()) *MockQuotaService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuotaService_DB_Call) Return(dB *gorm.DB) *MockQuotaService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockQuotaService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockQuotaService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// EnforceFundingTarget provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) EnforceFundingTarget(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for EnforceFundingTarget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaService_EnforceFundingTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnforceFundingTarget'
type MockQuotaService_EnforceFundingTarget_Call struct {
	*mock.Call
}

// EnforceFundingTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockQuotaService_Expecter) EnforceFundingTarget(ctx interface{}, userID interface{}) *MockQuotaService_EnforceFundingTarget_Call {
	return &MockQuotaService_EnforceFundingTarget_Call{Call: _e.mock.On("EnforceFundingTarget", ctx, userID)}
}

func (_c *MockQuotaService_EnforceFundingTarget_Call) Run(run func(ctx context.Context, userID uint)) *MockQuotaService_EnforceFundingTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaService_EnforceFundingTarget_Call) Return(err error) *MockQuotaService_EnforceFundingTarget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaService_EnforceFundingTarget_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockQuotaService_EnforceFundingTarget_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockQuotaService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockQuotaService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockQuotaService_Expecter) ID() *MockQuotaService_ID_Call {
	return &MockQuotaService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockQuotaService_ID_Call) Run(run func()) *MockQuotaService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuotaService_ID_Call) Return(s string) *MockQuotaService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockQuotaService_ID_Call) RunAndReturn(run func() string) *MockQuotaService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockQuotaService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockQuotaService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockQuotaService_Expecter) Logger() *MockQuotaService_Logger_Call {
	return &MockQuotaService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockQuotaService_Logger_Call) Run(run func()) *MockQuotaService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuotaService_Logger_Call) Return(logger *core.Logger) *MockQuotaService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockQuotaService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockQuotaService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// ProvisionAccount provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) ProvisionAccount(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ProvisionAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaService_ProvisionAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvisionAccount'
type MockQuotaService_ProvisionAccount_Call struct {
	*mock.Call
}

// ProvisionAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockQuotaService_Expecter) ProvisionAccount(ctx interface{}, userID interface{}) *MockQuotaService_ProvisionAccount_Call {
	return &MockQuotaService_ProvisionAccount_Call{Call: _e.mock.On("ProvisionAccount", ctx, userID)}
}

func (_c *MockQuotaService_ProvisionAccount_Call) Run(run func(ctx context.Context, userID uint)) *MockQuotaService_ProvisionAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuotaService_ProvisionAccount_Call) Return(err error) *MockQuotaService_ProvisionAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaService_ProvisionAccount_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockQuotaService_ProvisionAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockQuotaService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockQuotaService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockQuotaService_Expecter) SetConfig(cfg interface{}) *MockQuotaService_SetConfig_Call {
	return &MockQuotaService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockQuotaService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockQuotaService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaService_SetConfig_Call) Return() *MockQuotaService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQuotaService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockQuotaService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockQuotaService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockQuotaService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockQuotaService_Expecter) SetContext(ctx interface{}) *MockQuotaService_SetContext_Call {
	return &MockQuotaService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockQuotaService_SetContext_Call) Run(run func(ctx core.Context)) *MockQuotaService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaService_SetContext_Call) Return() *MockQuotaService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQuotaService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockQuotaService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockQuotaService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockQuotaService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockQuotaService_Expecter) SetDB(db interface{}) *MockQuotaService_SetDB_Call {
	return &MockQuotaService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockQuotaService_SetDB_Call) Run(run func(db *gorm.DB)) *MockQuotaService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaService_SetDB_Call) Return() *MockQuotaService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQuotaService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockQuotaService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockQuotaService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockQuotaService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockQuotaService_Expecter) SetLogger(logger interface{}) *MockQuotaService_SetLogger_Call {
	return &MockQuotaService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockQuotaService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockQuotaService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaService_SetLogger_Call) Return() *MockQuotaService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQuotaService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockQuotaService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SyncFunding provides a mock function for the type MockQuotaService
func (_mock *MockQuotaService) SyncFunding(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncFunding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaService_SyncFunding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncFunding'
type MockQuotaService_SyncFunding_Call struct {
	*mock.Call
}

// SyncFunding is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuotaService_Expecter) SyncFunding(ctx interface{}) *MockQuotaService_SyncFunding_Call {
	return &MockQuotaService_SyncFunding_Call{Call: _e.mock.On("SyncFunding", ctx)}
}

func (_c *MockQuotaService_SyncFunding_Call) Run(run func(ctx context.Context)) *MockQuotaService_SyncFunding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuotaService_SyncFunding_Call) Return(err error) *MockQuotaService_SyncFunding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaService_SyncFunding_Call) RunAndReturn(run func(ctx context.Context) error) *MockQuotaService_SyncFunding_Call {
	_c.Call.Return(run)
	return _c
}
