// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.sia.tech/core/rhp/v4"
	"go.sia.tech/indexd/accounts"
)

// NewMockAdminClient creates a new instance of MockAdminClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminClient {
	mock := &MockAdminClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminClient is an autogenerated mock type for the AdminClient type
type MockAdminClient struct {
	mock.Mock
}

type MockAdminClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminClient) EXPECT() *MockAdminClient_Expecter {
	return &MockAdminClient_Expecter{mock: &_m.Mock}
}

// AddAppConnectKey provides a mock function for the type MockAdminClient
func (_mock *MockAdminClient) AddAppConnectKey(ctx context.Context, req accounts.AppConnectKeyRequest) (accounts.ConnectKey, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddAppConnectKey")
	}

	var r0 accounts.ConnectKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, accounts.AppConnectKeyRequest) (accounts.ConnectKey, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, accounts.AppConnectKeyRequest) accounts.ConnectKey); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(accounts.ConnectKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, accounts.AppConnectKeyRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminClient_AddAppConnectKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAppConnectKey'
type MockAdminClient_AddAppConnectKey_Call struct {
	*mock.Call
}

// AddAppConnectKey is a helper method to define mock.On call
//   - ctx context.Context
//   - req accounts.AppConnectKeyRequest
func (_e *MockAdminClient_Expecter) AddAppConnectKey(ctx interface{}, req interface{}) *MockAdminClient_AddAppConnectKey_Call {
	return &MockAdminClient_AddAppConnectKey_Call{Call: _e.mock.On("AddAppConnectKey", ctx, req)}
}

func (_c *MockAdminClient_AddAppConnectKey_Call) Run(run func(ctx context.Context, req accounts.AppConnectKeyRequest)) *MockAdminClient_AddAppConnectKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 accounts.AppConnectKeyRequest
		if args[1] != nil {
			arg1 = args[1].(accounts.AppConnectKeyRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminClient_AddAppConnectKey_Call) Return(connectKey accounts.ConnectKey, err error) *MockAdminClient_AddAppConnectKey_Call {
	_c.Call.Return(connectKey, err)
	return _c
}

func (_c *MockAdminClient_AddAppConnectKey_Call) RunAndReturn(run func(ctx context.Context, req accounts.AppConnectKeyRequest) (accounts.ConnectKey, error)) *MockAdminClient_AddAppConnectKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function for the type MockAdminClient
func (_mock *MockAdminClient) DeleteAccount(ctx context.Context, acc rhp.Account) error {
	ret := _mock.Called(ctx, acc)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rhp.Account) error); ok {
		r0 = returnFunc(ctx, acc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminClient_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAdminClient_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - acc rhp.Account
func (_e *MockAdminClient_Expecter) DeleteAccount(ctx interface{}, acc interface{}) *MockAdminClient_DeleteAccount_Call {
	return &MockAdminClient_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, acc)}
}

func (_c *MockAdminClient_DeleteAccount_Call) Run(run func(ctx context.Context, acc rhp.Account)) *MockAdminClient_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rhp.Account
		if args[1] != nil {
			arg1 = args[1].(rhp.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminClient_DeleteAccount_Call) Return(err error) *MockAdminClient_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminClient_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, acc rhp.Account) error) *MockAdminClient_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAppConnectKey provides a mock function for the type MockAdminClient
func (_mock *MockAdminClient) DeleteAppConnectKey(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppConnectKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminClient_DeleteAppConnectKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAppConnectKey'
type MockAdminClient_DeleteAppConnectKey_Call struct {
	*mock.Call
}

// DeleteAppConnectKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAdminClient_Expecter) DeleteAppConnectKey(ctx interface{}, key interface{}) *MockAdminClient_DeleteAppConnectKey_Call {
	return &MockAdminClient_DeleteAppConnectKey_Call{Call: _e.mock.On("DeleteAppConnectKey", ctx, key)}
}

func (_c *MockAdminClient_DeleteAppConnectKey_Call) Run(run func(ctx context.Context, key string)) *MockAdminClient_DeleteAppConnectKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminClient_DeleteAppConnectKey_Call) Return(err error) *MockAdminClient_DeleteAppConnectKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminClient_DeleteAppConnectKey_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockAdminClient_DeleteAppConnectKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuota provides a mock function for the type MockAdminClient
func (_mock *MockAdminClient) DeleteQuota(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuota")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminClient_DeleteQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuota'
type MockAdminClient_DeleteQuota_Call struct {
	*mock.Call
}

// DeleteQuota is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAdminClient_Expecter) DeleteQuota(ctx interface{}, key interface{}) *MockAdminClient_DeleteQuota_Call {
	return &MockAdminClient_DeleteQuota_Call{Call: _e.mock.On("DeleteQuota", ctx, key)}
}

func (_c *MockAdminClient_DeleteQuota_Call) Run(run func(ctx context.Context, key string)) *MockAdminClient_DeleteQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminClient_DeleteQuota_Call) Return(err error) *MockAdminClient_DeleteQuota_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminClient_DeleteQuota_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockAdminClient_DeleteQuota_Call {
	_c.Call.Return(run)
	return _c
}

// FundingEvents provides a mock function for the type MockAdminClient
func (_mock *MockAdminClient) FundingEvents(ctx context.Context, cursor accounts.FundingCursor, limit int) ([]accounts.FundingEvent, error) {
	ret := _mock.Called(ctx, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for FundingEvents")
	}

	var r0 []accounts.FundingEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, accounts.FundingCursor, int) ([]accounts.FundingEvent, error)); ok {
		return returnFunc(ctx, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, accounts.FundingCursor, int) []accounts.FundingEvent); ok {
		r0 = returnFunc(ctx, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]accounts.FundingEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, accounts.FundingCursor, int) error); ok {
		r1 = returnFunc(ctx, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminClient_FundingEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FundingEvents'
type MockAdminClient_FundingEvents_Call struct {
	*mock.Call
}

// FundingEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - cursor accounts.FundingCursor
//   - limit int
func (_e *MockAdminClient_Expecter) FundingEvents(ctx interface{}, cursor interface{}, limit interface{}) *MockAdminClient_FundingEvents_Call {
	return &MockAdminClient_FundingEvents_Call{Call: _e.mock.On("FundingEvents", ctx, cursor, limit)}
}

func (_c *MockAdminClient_FundingEvents_Call) Run(run func(ctx context.Context, cursor accounts.FundingCursor, limit int)) *MockAdminClient_FundingEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 accounts.FundingCursor
		if args[1] != nil {
			arg1 = args[1].(accounts.FundingCursor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminClient_FundingEvents_Call) Return(fundingEvents []accounts.FundingEvent, err error) *MockAdminClient_FundingEvents_Call {
	_c.Call.Return(fundingEvents, err)
	return _c
}

func (_c *MockAdminClient_FundingEvents_Call) RunAndReturn(run func(ctx context.Context, cursor accounts.FundingCursor, limit int) ([]accounts.FundingEvent, error)) *MockAdminClient_FundingEvents_Call {
	_c.Call.Return(run)
	return _c
}

// PutQuota provides a mock function for the type MockAdminClient
func (_mock *MockAdminClient) PutQuota(ctx context.Context, key string, req accounts.PutQuotaRequest) error {
	ret := _mock.Called(ctx, key, req)

	if len(ret) == 0 {
		panic("no return value specified for PutQuota")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, accounts.PutQuotaRequest) error); ok {
		r0 = returnFunc(ctx, key, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminClient_PutQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutQuota'
type MockAdminClient_PutQuota_Call struct {
	*mock.Call
}

// PutQuota is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - req accounts.PutQuotaRequest
func (_e *MockAdminClient_Expecter) PutQuota(ctx interface{}, key interface{}, req interface{}) *MockAdminClient_PutQuota_Call {
	return &MockAdminClient_PutQuota_Call{Call: _e.mock.On("PutQuota", ctx, key, req)}
}

func (_c *MockAdminClient_PutQuota_Call) Run(run func(ctx context.Context, key string, req accounts.PutQuotaRequest)) *MockAdminClient_PutQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 accounts.PutQuotaRequest
		if args[2] != nil {
			arg2 = args[2].(accounts.PutQuotaRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminClient_PutQuota_Call) Return(err error) *MockAdminClient_PutQuota_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminClient_PutQuota_Call) RunAndReturn(run func(ctx context.Context, key string, req accounts.PutQuotaRequest) error) *MockAdminClient_PutQuota_Call {
	_c.Call.Return(run)
	return _c
}

// Quota provides a mock function for the type MockAdminClient
func (_mock *MockAdminClient) Quota(ctx context.Context, key string) (accounts.Quota, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Quota")
	}

	var r0 accounts.Quota
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (accounts.Quota, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) accounts.Quota); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(accounts.Quota)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminClient_Quota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Quota'
type MockAdminClient_Quota_Call struct {
	*mock.Call
}

// Quota is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAdminClient_Expecter) Quota(ctx interface{}, key interface{}) *MockAdminClient_Quota_Call {
	return &MockAdminClient_Quota_Call{Call: _e.mock.On("Quota", ctx, key)}
}

func (_c *MockAdminClient_Quota_Call) Run(run func(ctx context.Context, key string)) *MockAdminClient_Quota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminClient_Quota_Call) Return(quota accounts.Quota, err error) *MockAdminClient_Quota_Call {
	_c.Call.Return(quota, err)
	return _c
}

func (_c *MockAdminClient_Quota_Call) RunAndReturn(run func(ctx context.Context, key string) (accounts.Quota, error)) *MockAdminClient_Quota_Call {
	_c.Call.Return(run)
	return _c
}
