// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	accounts "go.sia.tech/indexd/accounts"
	admin "go.sia.tech/indexd/api/admin"

	api "go.sia.tech/indexd/api"

	context "context"

	contracts "go.sia.tech/indexd/contracts"

	hosts "go.sia.tech/indexd/hosts"

	mock "github.com/stretchr/testify/mock"

	rhp "go.sia.tech/core/rhp/v4"

	types "go.sia.tech/core/types"
)

// MockAdminClient is an autogenerated mock type for the AdminClient type
type MockAdminClient struct {
	mock.Mock
}

type MockAdminClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminClient) EXPECT() *MockAdminClient_Expecter {
	return &MockAdminClient_Expecter{mock: &_m.Mock}
}

// Account provides a mock function with given fields: ctx, ak
func (_m *MockAdminClient) Account(ctx context.Context, ak types.PublicKey) (accounts.Account, error) {
	ret := _m.Called(ctx, ak)

	if len(ret) == 0 {
		panic("no return value specified for Account")
	}

	var r0 accounts.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.PublicKey) (accounts.Account, error)); ok {
		return rf(ctx, ak)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.PublicKey) accounts.Account); ok {
		r0 = rf(ctx, ak)
	} else {
		r0 = ret.Get(0).(accounts.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.PublicKey) error); ok {
		r1 = rf(ctx, ak)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminClient_Account_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Account'
type MockAdminClient_Account_Call struct {
	*mock.Call
}

// Account is a helper method to define mock.On call
//   - ctx context.Context
//   - ak types.PublicKey
func (_e *MockAdminClient_Expecter) Account(ctx interface{}, ak interface{}) *MockAdminClient_Account_Call {
	return &MockAdminClient_Account_Call{Call: _e.mock.On("Account", ctx, ak)}
}

func (_c *MockAdminClient_Account_Call) Run(run func(ctx context.Context, ak types.PublicKey)) *MockAdminClient_Account_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.PublicKey))
	})
	return _c
}

func (_c *MockAdminClient_Account_Call) Return(_a0 accounts.Account, _a1 error) *MockAdminClient_Account_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminClient_Account_Call) RunAndReturn(run func(context.Context, types.PublicKey) (accounts.Account, error)) *MockAdminClient_Account_Call {
	_c.Call.Return(run)
	return _c
}

// Accounts provides a mock function with given fields: ctx, opts
func (_m *MockAdminClient) Accounts(ctx context.Context, opts ...api.URLQueryParameterOption) ([]accounts.Account, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Accounts")
	}

	var r0 []accounts.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...api.URLQueryParameterOption) ([]accounts.Account, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...api.URLQueryParameterOption) []accounts.Account); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]accounts.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...api.URLQueryParameterOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminClient_Accounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accounts'
type MockAdminClient_Accounts_Call struct {
	*mock.Call
}

// Accounts is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...api.URLQueryParameterOption
func (_e *MockAdminClient_Expecter) Accounts(ctx interface{}, opts ...interface{}) *MockAdminClient_Accounts_Call {
	return &MockAdminClient_Accounts_Call{Call: _e.mock.On("Accounts",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAdminClient_Accounts_Call) Run(run func(ctx context.Context, opts ...api.URLQueryParameterOption)) *MockAdminClient_Accounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]api.URLQueryParameterOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(api.URLQueryParameterOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockAdminClient_Accounts_Call) Return(_a0 []accounts.Account, _a1 error) *MockAdminClient_Accounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminClient_Accounts_Call) RunAndReturn(run func(context.Context, ...api.URLQueryParameterOption) ([]accounts.Account, error)) *MockAdminClient_Accounts_Call {
	_c.Call.Return(run)
	return _c
}

// AddAppConnectKey provides a mock function with given fields: ctx, req
func (_m *MockAdminClient) AddAppConnectKey(ctx context.Context, req accounts.AppConnectKeyRequest) (accounts.ConnectKey, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddAppConnectKey")
	}

	var r0 accounts.ConnectKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, accounts.AppConnectKeyRequest) (accounts.ConnectKey, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, accounts.AppConnectKeyRequest) accounts.ConnectKey); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(accounts.ConnectKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, accounts.AppConnectKeyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminClient_AddAppConnectKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAppConnectKey'
type MockAdminClient_AddAppConnectKey_Call struct {
	*mock.Call
}

// AddAppConnectKey is a helper method to define mock.On call
//   - ctx context.Context
//   - req accounts.AppConnectKeyRequest
func (_e *MockAdminClient_Expecter) AddAppConnectKey(ctx interface{}, req interface{}) *MockAdminClient_AddAppConnectKey_Call {
	return &MockAdminClient_AddAppConnectKey_Call{Call: _e.mock.On("AddAppConnectKey", ctx, req)}
}

func (_c *MockAdminClient_AddAppConnectKey_Call) Run(run func(ctx context.Context, req accounts.AppConnectKeyRequest)) *MockAdminClient_AddAppConnectKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(accounts.AppConnectKeyRequest))
	})
	return _c
}

func (_c *MockAdminClient_AddAppConnectKey_Call) Return(_a0 accounts.ConnectKey, _a1 error) *MockAdminClient_AddAppConnectKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminClient_AddAppConnectKey_Call) RunAndReturn(run func(context.Context, accounts.AppConnectKeyRequest) (accounts.ConnectKey, error)) *MockAdminClient_AddAppConnectKey_Call {
	_c.Call.Return(run)
	return _c
}

// Contracts provides a mock function with given fields: ctx, opts
func (_m *MockAdminClient) Contracts(ctx context.Context, opts ...admin.ContractQueryParameterOption) ([]contracts.Contract, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Contracts")
	}

	var r0 []contracts.Contract
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...admin.ContractQueryParameterOption) ([]contracts.Contract, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...admin.ContractQueryParameterOption) []contracts.Contract); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.Contract)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...admin.ContractQueryParameterOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminClient_Contracts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Contracts'
type MockAdminClient_Contracts_Call struct {
	*mock.Call
}

// Contracts is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...admin.ContractQueryParameterOption
func (_e *MockAdminClient_Expecter) Contracts(ctx interface{}, opts ...interface{}) *MockAdminClient_Contracts_Call {
	return &MockAdminClient_Contracts_Call{Call: _e.mock.On("Contracts",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAdminClient_Contracts_Call) Run(run func(ctx context.Context, opts ...admin.ContractQueryParameterOption)) *MockAdminClient_Contracts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]admin.ContractQueryParameterOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(admin.ContractQueryParameterOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockAdminClient_Contracts_Call) Return(_a0 []contracts.Contract, _a1 error) *MockAdminClient_Contracts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminClient_Contracts_Call) RunAndReturn(run func(context.Context, ...admin.ContractQueryParameterOption) ([]contracts.Contract, error)) *MockAdminClient_Contracts_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, acc
func (_m *MockAdminClient) DeleteAccount(ctx context.Context, acc rhp.Account) error {
	ret := _m.Called(ctx, acc)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rhp.Account) error); ok {
		r0 = rf(ctx, acc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminClient_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAdminClient_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - acc rhp.Account
func (_e *MockAdminClient_Expecter) DeleteAccount(ctx interface{}, acc interface{}) *MockAdminClient_DeleteAccount_Call {
	return &MockAdminClient_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, acc)}
}

func (_c *MockAdminClient_DeleteAccount_Call) Run(run func(ctx context.Context, acc rhp.Account)) *MockAdminClient_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rhp.Account))
	})
	return _c
}

func (_c *MockAdminClient_DeleteAccount_Call) Return(_a0 error) *MockAdminClient_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminClient_DeleteAccount_Call) RunAndReturn(run func(context.Context, rhp.Account) error) *MockAdminClient_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAppConnectKey provides a mock function with given fields: ctx, key
func (_m *MockAdminClient) DeleteAppConnectKey(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppConnectKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminClient_DeleteAppConnectKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAppConnectKey'
type MockAdminClient_DeleteAppConnectKey_Call struct {
	*mock.Call
}

// DeleteAppConnectKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAdminClient_Expecter) DeleteAppConnectKey(ctx interface{}, key interface{}) *MockAdminClient_DeleteAppConnectKey_Call {
	return &MockAdminClient_DeleteAppConnectKey_Call{Call: _e.mock.On("DeleteAppConnectKey", ctx, key)}
}

func (_c *MockAdminClient_DeleteAppConnectKey_Call) Run(run func(ctx context.Context, key string)) *MockAdminClient_DeleteAppConnectKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminClient_DeleteAppConnectKey_Call) Return(_a0 error) *MockAdminClient_DeleteAppConnectKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminClient_DeleteAppConnectKey_Call) RunAndReturn(run func(context.Context, string) error) *MockAdminClient_DeleteAppConnectKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuota provides a mock function with given fields: ctx, key
func (_m *MockAdminClient) DeleteQuota(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuota")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminClient_DeleteQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuota'
type MockAdminClient_DeleteQuota_Call struct {
	*mock.Call
}

// DeleteQuota is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAdminClient_Expecter) DeleteQuota(ctx interface{}, key interface{}) *MockAdminClient_DeleteQuota_Call {
	return &MockAdminClient_DeleteQuota_Call{Call: _e.mock.On("DeleteQuota", ctx, key)}
}

func (_c *MockAdminClient_DeleteQuota_Call) Run(run func(ctx context.Context, key string)) *MockAdminClient_DeleteQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminClient_DeleteQuota_Call) Return(_a0 error) *MockAdminClient_DeleteQuota_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminClient_DeleteQuota_Call) RunAndReturn(run func(context.Context, string) error) *MockAdminClient_DeleteQuota_Call {
	_c.Call.Return(run)
	return _c
}

// FundingEvents provides a mock function with given fields: ctx, cursor, limit
func (_m *MockAdminClient) FundingEvents(ctx context.Context, cursor accounts.FundingCursor, limit int) ([]accounts.FundingEvent, error) {
	ret := _m.Called(ctx, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for FundingEvents")
	}

	var r0 []accounts.FundingEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, accounts.FundingCursor, int) ([]accounts.FundingEvent, error)); ok {
		return rf(ctx, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, accounts.FundingCursor, int) []accounts.FundingEvent); ok {
		r0 = rf(ctx, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]accounts.FundingEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, accounts.FundingCursor, int) error); ok {
		r1 = rf(ctx, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminClient_FundingEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FundingEvents'
type MockAdminClient_FundingEvents_Call struct {
	*mock.Call
}

// FundingEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - cursor accounts.FundingCursor
//   - limit int
func (_e *MockAdminClient_Expecter) FundingEvents(ctx interface{}, cursor interface{}, limit interface{}) *MockAdminClient_FundingEvents_Call {
	return &MockAdminClient_FundingEvents_Call{Call: _e.mock.On("FundingEvents", ctx, cursor, limit)}
}

func (_c *MockAdminClient_FundingEvents_Call) Run(run func(ctx context.Context, cursor accounts.FundingCursor, limit int)) *MockAdminClient_FundingEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(accounts.FundingCursor), args[2].(int))
	})
	return _c
}

func (_c *MockAdminClient_FundingEvents_Call) Return(_a0 []accounts.FundingEvent, _a1 error) *MockAdminClient_FundingEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminClient_FundingEvents_Call) RunAndReturn(run func(context.Context, accounts.FundingCursor, int) ([]accounts.FundingEvent, error)) *MockAdminClient_FundingEvents_Call {
	_c.Call.Return(run)
	return _c
}

// Hosts provides a mock function with given fields: ctx, opts
func (_m *MockAdminClient) Hosts(ctx context.Context, opts ...admin.HostQueryParameterOption) ([]hosts.Host, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Hosts")
	}

	var r0 []hosts.Host
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...admin.HostQueryParameterOption) ([]hosts.Host, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...admin.HostQueryParameterOption) []hosts.Host); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hosts.Host)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...admin.HostQueryParameterOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminClient_Hosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hosts'
type MockAdminClient_Hosts_Call struct {
	*mock.Call
}

// Hosts is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...admin.HostQueryParameterOption
func (_e *MockAdminClient_Expecter) Hosts(ctx interface{}, opts ...interface{}) *MockAdminClient_Hosts_Call {
	return &MockAdminClient_Hosts_Call{Call: _e.mock.On("Hosts",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAdminClient_Hosts_Call) Run(run func(ctx context.Context, opts ...admin.HostQueryParameterOption)) *MockAdminClient_Hosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]admin.HostQueryParameterOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(admin.HostQueryParameterOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockAdminClient_Hosts_Call) Return(_a0 []hosts.Host, _a1 error) *MockAdminClient_Hosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminClient_Hosts_Call) RunAndReturn(run func(context.Context, ...admin.HostQueryParameterOption) ([]hosts.Host, error)) *MockAdminClient_Hosts_Call {
	_c.Call.Return(run)
	return _c
}

// PruneSlabs provides a mock function with given fields: ctx, ak, opts
func (_m *MockAdminClient) PruneSlabs(ctx context.Context, ak types.PublicKey, opts ...api.URLQueryParameterOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, ak)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PruneSlabs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.PublicKey, ...api.URLQueryParameterOption) error); ok {
		r0 = rf(ctx, ak, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminClient_PruneSlabs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneSlabs'
type MockAdminClient_PruneSlabs_Call struct {
	*mock.Call
}

// PruneSlabs is a helper method to define mock.On call
//   - ctx context.Context
//   - ak types.PublicKey
//   - opts ...api.URLQueryParameterOption
func (_e *MockAdminClient_Expecter) PruneSlabs(ctx interface{}, ak interface{}, opts ...interface{}) *MockAdminClient_PruneSlabs_Call {
	return &MockAdminClient_PruneSlabs_Call{Call: _e.mock.On("PruneSlabs",
		append([]interface{}{ctx, ak}, opts...)...)}
}

func (_c *MockAdminClient_PruneSlabs_Call) Run(run func(ctx context.Context, ak types.PublicKey, opts ...api.URLQueryParameterOption)) *MockAdminClient_PruneSlabs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]api.URLQueryParameterOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(api.URLQueryParameterOption)
			}
		}
		run(args[0].(context.Context), args[1].(types.PublicKey), variadicArgs...)
	})
	return _c
}

func (_c *MockAdminClient_PruneSlabs_Call) Return(_a0 error) *MockAdminClient_PruneSlabs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminClient_PruneSlabs_Call) RunAndReturn(run func(context.Context, types.PublicKey, ...api.URLQueryParameterOption) error) *MockAdminClient_PruneSlabs_Call {
	_c.Call.Return(run)
	return _c
}

// PutQuota provides a mock function with given fields: ctx, key, req
func (_m *MockAdminClient) PutQuota(ctx context.Context, key string, req accounts.PutQuotaRequest) error {
	ret := _m.Called(ctx, key, req)

	if len(ret) == 0 {
		panic("no return value specified for PutQuota")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, accounts.PutQuotaRequest) error); ok {
		r0 = rf(ctx, key, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminClient_PutQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutQuota'
type MockAdminClient_PutQuota_Call struct {
	*mock.Call
}

// PutQuota is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - req accounts.PutQuotaRequest
func (_e *MockAdminClient_Expecter) PutQuota(ctx interface{}, key interface{}, req interface{}) *MockAdminClient_PutQuota_Call {
	return &MockAdminClient_PutQuota_Call{Call: _e.mock.On("PutQuota", ctx, key, req)}
}

func (_c *MockAdminClient_PutQuota_Call) Run(run func(ctx context.Context, key string, req accounts.PutQuotaRequest)) *MockAdminClient_PutQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(accounts.PutQuotaRequest))
	})
	return _c
}

func (_c *MockAdminClient_PutQuota_Call) Return(_a0 error) *MockAdminClient_PutQuota_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminClient_PutQuota_Call) RunAndReturn(run func(context.Context, string, accounts.PutQuotaRequest) error) *MockAdminClient_PutQuota_Call {
	_c.Call.Return(run)
	return _c
}

// Quota provides a mock function with given fields: ctx, key
func (_m *MockAdminClient) Quota(ctx context.Context, key string) (accounts.Quota, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Quota")
	}

	var r0 accounts.Quota
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (accounts.Quota, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) accounts.Quota); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(accounts.Quota)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminClient_Quota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Quota'
type MockAdminClient_Quota_Call struct {
	*mock.Call
}

// Quota is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAdminClient_Expecter) Quota(ctx interface{}, key interface{}) *MockAdminClient_Quota_Call {
	return &MockAdminClient_Quota_Call{Call: _e.mock.On("Quota", ctx, key)}
}

func (_c *MockAdminClient_Quota_Call) Run(run func(ctx context.Context, key string)) *MockAdminClient_Quota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminClient_Quota_Call) Return(_a0 accounts.Quota, _a1 error) *MockAdminClient_Quota_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminClient_Quota_Call) RunAndReturn(run func(context.Context, string) (accounts.Quota, error)) *MockAdminClient_Quota_Call {
	_c.Call.Return(run)
	return _c
}

// StatsApps provides a mock function with given fields: ctx, offset, limit
func (_m *MockAdminClient) StatsApps(ctx context.Context, offset int, limit int) (admin.AppStatsResponse, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for StatsApps")
	}

	var r0 admin.AppStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (admin.AppStatsResponse, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) admin.AppStatsResponse); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(admin.AppStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminClient_StatsApps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatsApps'
type MockAdminClient_StatsApps_Call struct {
	*mock.Call
}

// StatsApps is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockAdminClient_Expecter) StatsApps(ctx interface{}, offset interface{}, limit interface{}) *MockAdminClient_StatsApps_Call {
	return &MockAdminClient_StatsApps_Call{Call: _e.mock.On("StatsApps", ctx, offset, limit)}
}

func (_c *MockAdminClient_StatsApps_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockAdminClient_StatsApps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAdminClient_StatsApps_Call) Return(_a0 admin.AppStatsResponse, _a1 error) *MockAdminClient_StatsApps_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminClient_StatsApps_Call) RunAndReturn(run func(context.Context, int, int) (admin.AppStatsResponse, error)) *MockAdminClient_StatsApps_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminClient creates a new instance of MockAdminClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminClient {
	mock := &MockAdminClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
