// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	config "go.lumeweb.com/portal/config"

	core "go.lumeweb.com/portal-plugin-sia/core"

	db "go.lumeweb.com/portal-plugin-sia/internal/db"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	portalcore "go.lumeweb.com/portal/core"

	types "go.sia.tech/core/types"
)

// MockSiaService is an autogenerated mock type for the SiaService type
type MockSiaService struct {
	mock.Mock
}

type MockSiaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSiaService) EXPECT() *MockSiaService_Expecter {
	return &MockSiaService_Expecter{mock: &_m.Mock}
}

// AccountExists provides a mock function with given fields: ctx, userID
func (_m *MockSiaService) AccountExists(ctx context.Context, userID uint) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AccountExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_AccountExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountExists'
type MockSiaService_AccountExists_Call struct {
	*mock.Call
}

// AccountExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSiaService_Expecter) AccountExists(ctx interface{}, userID interface{}) *MockSiaService_AccountExists_Call {
	return &MockSiaService_AccountExists_Call{Call: _e.mock.On("AccountExists", ctx, userID)}
}

func (_c *MockSiaService_AccountExists_Call) Run(run func(ctx context.Context, userID uint)) *MockSiaService_AccountExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_AccountExists_Call) Return(_a0 bool, _a1 error) *MockSiaService_AccountExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_AccountExists_Call) RunAndReturn(run func(context.Context, uint) (bool, error)) *MockSiaService_AccountExists_Call {
	_c.Call.Return(run)
	return _c
}

// AdminClient provides a mock function with no fields
func (_m *MockSiaService) AdminClient() core.AdminClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AdminClient")
	}

	var r0 core.AdminClient
	if rf, ok := ret.Get(0).(func() core.AdminClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.AdminClient)
		}
	}

	return r0
}

// MockSiaService_AdminClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminClient'
type MockSiaService_AdminClient_Call struct {
	*mock.Call
}

// AdminClient is a helper method to define mock.On call
func (_e *MockSiaService_Expecter) AdminClient() *MockSiaService_AdminClient_Call {
	return &MockSiaService_AdminClient_Call{Call: _e.mock.On("AdminClient")}
}

func (_c *MockSiaService_AdminClient_Call) Run(run func()) *MockSiaService_AdminClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSiaService_AdminClient_Call) Return(_a0 core.AdminClient) *MockSiaService_AdminClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_AdminClient_Call) RunAndReturn(run func() core.AdminClient) *MockSiaService_AdminClient_Call {
	_c.Call.Return(run)
	return _c
}

// CleanupExpiredAuthRequests provides a mock function with given fields: ctx
func (_m *MockSiaService) CleanupExpiredAuthRequests(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpiredAuthRequests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_CleanupExpiredAuthRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExpiredAuthRequests'
type MockSiaService_CleanupExpiredAuthRequests_Call struct {
	*mock.Call
}

// CleanupExpiredAuthRequests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSiaService_Expecter) CleanupExpiredAuthRequests(ctx interface{}) *MockSiaService_CleanupExpiredAuthRequests_Call {
	return &MockSiaService_CleanupExpiredAuthRequests_Call{Call: _e.mock.On("CleanupExpiredAuthRequests", ctx)}
}

func (_c *MockSiaService_CleanupExpiredAuthRequests_Call) Run(run func(ctx context.Context)) *MockSiaService_CleanupExpiredAuthRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSiaService_CleanupExpiredAuthRequests_Call) Return(_a0 error) *MockSiaService_CleanupExpiredAuthRequests_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_CleanupExpiredAuthRequests_Call) RunAndReturn(run func(context.Context) error) *MockSiaService_CleanupExpiredAuthRequests_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function with no fields
func (_m *MockSiaService) Config() config.Manager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if rf, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}

	return r0
}

// MockSiaService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockSiaService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockSiaService_Expecter) Config() *MockSiaService_Config_Call {
	return &MockSiaService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockSiaService_Config_Call) Run(run func()) *MockSiaService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSiaService_Config_Call) Return(_a0 config.Manager) *MockSiaService_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_Config_Call) RunAndReturn(run func() config.Manager) *MockSiaService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with no fields
func (_m *MockSiaService) Context() portalcore.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 portalcore.Context
	if rf, ok := ret.Get(0).(func() portalcore.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(portalcore.Context)
		}
	}

	return r0
}

// MockSiaService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockSiaService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockSiaService_Expecter) Context() *MockSiaService_Context_Call {
	return &MockSiaService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockSiaService_Context_Call) Run(run func()) *MockSiaService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSiaService_Context_Call) Return(_a0 portalcore.Context) *MockSiaService_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_Context_Call) RunAndReturn(run func() portalcore.Context) *MockSiaService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function with no fields
func (_m *MockSiaService) DB() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// MockSiaService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockSiaService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockSiaService_Expecter) DB() *MockSiaService_DB_Call {
	return &MockSiaService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockSiaService_DB_Call) Run(run func()) *MockSiaService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSiaService_DB_Call) Return(_a0 *gorm.DB) *MockSiaService_DB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockSiaService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, userID
func (_m *MockSiaService) DeleteAccount(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockSiaService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSiaService_Expecter) DeleteAccount(ctx interface{}, userID interface{}) *MockSiaService_DeleteAccount_Call {
	return &MockSiaService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, userID)}
}

func (_c *MockSiaService_DeleteAccount_Call) Run(run func(ctx context.Context, userID uint)) *MockSiaService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_DeleteAccount_Call) Return(_a0 error) *MockSiaService_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DeleteAccount_Call) RunAndReturn(run func(context.Context, uint) error) *MockSiaService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAppAccount provides a mock function with given fields: ctx, siaAccountID, accountKey
func (_m *MockSiaService) DeleteAppAccount(ctx context.Context, siaAccountID uint, accountKey types.PublicKey) error {
	ret := _m.Called(ctx, siaAccountID, accountKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, types.PublicKey) error); ok {
		r0 = rf(ctx, siaAccountID, accountKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_DeleteAppAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAppAccount'
type MockSiaService_DeleteAppAccount_Call struct {
	*mock.Call
}

// DeleteAppAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAccountID uint
//   - accountKey types.PublicKey
func (_e *MockSiaService_Expecter) DeleteAppAccount(ctx interface{}, siaAccountID interface{}, accountKey interface{}) *MockSiaService_DeleteAppAccount_Call {
	return &MockSiaService_DeleteAppAccount_Call{Call: _e.mock.On("DeleteAppAccount", ctx, siaAccountID, accountKey)}
}

func (_c *MockSiaService_DeleteAppAccount_Call) Run(run func(ctx context.Context, siaAccountID uint, accountKey types.PublicKey)) *MockSiaService_DeleteAppAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(types.PublicKey))
	})
	return _c
}

func (_c *MockSiaService_DeleteAppAccount_Call) Return(_a0 error) *MockSiaService_DeleteAppAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DeleteAppAccount_Call) RunAndReturn(run func(context.Context, uint, types.PublicKey) error) *MockSiaService_DeleteAppAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAppAccountsBySiaAccountID provides a mock function with given fields: ctx, siaAccountID
func (_m *MockSiaService) DeleteAppAccountsBySiaAccountID(ctx context.Context, siaAccountID uint) error {
	ret := _m.Called(ctx, siaAccountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppAccountsBySiaAccountID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, siaAccountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_DeleteAppAccountsBySiaAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAppAccountsBySiaAccountID'
type MockSiaService_DeleteAppAccountsBySiaAccountID_Call struct {
	*mock.Call
}

// DeleteAppAccountsBySiaAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAccountID uint
func (_e *MockSiaService_Expecter) DeleteAppAccountsBySiaAccountID(ctx interface{}, siaAccountID interface{}) *MockSiaService_DeleteAppAccountsBySiaAccountID_Call {
	return &MockSiaService_DeleteAppAccountsBySiaAccountID_Call{Call: _e.mock.On("DeleteAppAccountsBySiaAccountID", ctx, siaAccountID)}
}

func (_c *MockSiaService_DeleteAppAccountsBySiaAccountID_Call) Run(run func(ctx context.Context, siaAccountID uint)) *MockSiaService_DeleteAppAccountsBySiaAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_DeleteAppAccountsBySiaAccountID_Call) Return(_a0 error) *MockSiaService_DeleteAppAccountsBySiaAccountID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DeleteAppAccountsBySiaAccountID_Call) RunAndReturn(run func(context.Context, uint) error) *MockSiaService_DeleteAppAccountsBySiaAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAuthRequest provides a mock function with given fields: ctx, requestID
func (_m *MockSiaService) DeleteAuthRequest(ctx context.Context, requestID string) error {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAuthRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_DeleteAuthRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAuthRequest'
type MockSiaService_DeleteAuthRequest_Call struct {
	*mock.Call
}

// DeleteAuthRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
func (_e *MockSiaService_Expecter) DeleteAuthRequest(ctx interface{}, requestID interface{}) *MockSiaService_DeleteAuthRequest_Call {
	return &MockSiaService_DeleteAuthRequest_Call{Call: _e.mock.On("DeleteAuthRequest", ctx, requestID)}
}

func (_c *MockSiaService_DeleteAuthRequest_Call) Run(run func(ctx context.Context, requestID string)) *MockSiaService_DeleteAuthRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSiaService_DeleteAuthRequest_Call) Return(_a0 error) *MockSiaService_DeleteAuthRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DeleteAuthRequest_Call) RunAndReturn(run func(context.Context, string) error) *MockSiaService_DeleteAuthRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function with given fields: ctx, siaAppAccountID, objectID
func (_m *MockSiaService) DeleteObject(ctx context.Context, siaAppAccountID uint, objectID string) error {
	ret := _m.Called(ctx, siaAppAccountID, objectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, siaAppAccountID, objectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockSiaService_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
//   - objectID string
func (_e *MockSiaService_Expecter) DeleteObject(ctx interface{}, siaAppAccountID interface{}, objectID interface{}) *MockSiaService_DeleteObject_Call {
	return &MockSiaService_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, siaAppAccountID, objectID)}
}

func (_c *MockSiaService_DeleteObject_Call) Run(run func(ctx context.Context, siaAppAccountID uint, objectID string)) *MockSiaService_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockSiaService_DeleteObject_Call) Return(_a0 error) *MockSiaService_DeleteObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DeleteObject_Call) RunAndReturn(run func(context.Context, uint, string) error) *MockSiaService_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObjectsByAppAccount provides a mock function with given fields: ctx, siaAppAccountID
func (_m *MockSiaService) DeleteObjectsByAppAccount(ctx context.Context, siaAppAccountID uint) error {
	ret := _m.Called(ctx, siaAppAccountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjectsByAppAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, siaAppAccountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_DeleteObjectsByAppAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjectsByAppAccount'
type MockSiaService_DeleteObjectsByAppAccount_Call struct {
	*mock.Call
}

// DeleteObjectsByAppAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
func (_e *MockSiaService_Expecter) DeleteObjectsByAppAccount(ctx interface{}, siaAppAccountID interface{}) *MockSiaService_DeleteObjectsByAppAccount_Call {
	return &MockSiaService_DeleteObjectsByAppAccount_Call{Call: _e.mock.On("DeleteObjectsByAppAccount", ctx, siaAppAccountID)}
}

func (_c *MockSiaService_DeleteObjectsByAppAccount_Call) Run(run func(ctx context.Context, siaAppAccountID uint)) *MockSiaService_DeleteObjectsByAppAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_DeleteObjectsByAppAccount_Call) Return(_a0 error) *MockSiaService_DeleteObjectsByAppAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DeleteObjectsByAppAccount_Call) RunAndReturn(run func(context.Context, uint) error) *MockSiaService_DeleteObjectsByAppAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSlab provides a mock function with given fields: ctx, siaAppAccountID, slabID
func (_m *MockSiaService) DeleteSlab(ctx context.Context, siaAppAccountID uint, slabID string) error {
	ret := _m.Called(ctx, siaAppAccountID, slabID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSlab")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, siaAppAccountID, slabID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_DeleteSlab_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSlab'
type MockSiaService_DeleteSlab_Call struct {
	*mock.Call
}

// DeleteSlab is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
//   - slabID string
func (_e *MockSiaService_Expecter) DeleteSlab(ctx interface{}, siaAppAccountID interface{}, slabID interface{}) *MockSiaService_DeleteSlab_Call {
	return &MockSiaService_DeleteSlab_Call{Call: _e.mock.On("DeleteSlab", ctx, siaAppAccountID, slabID)}
}

func (_c *MockSiaService_DeleteSlab_Call) Run(run func(ctx context.Context, siaAppAccountID uint, slabID string)) *MockSiaService_DeleteSlab_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockSiaService_DeleteSlab_Call) Return(_a0 error) *MockSiaService_DeleteSlab_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DeleteSlab_Call) RunAndReturn(run func(context.Context, uint, string) error) *MockSiaService_DeleteSlab_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSlabsByAppAccount provides a mock function with given fields: ctx, siaAppAccountID
func (_m *MockSiaService) DeleteSlabsByAppAccount(ctx context.Context, siaAppAccountID uint) error {
	ret := _m.Called(ctx, siaAppAccountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSlabsByAppAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, siaAppAccountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_DeleteSlabsByAppAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSlabsByAppAccount'
type MockSiaService_DeleteSlabsByAppAccount_Call struct {
	*mock.Call
}

// DeleteSlabsByAppAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
func (_e *MockSiaService_Expecter) DeleteSlabsByAppAccount(ctx interface{}, siaAppAccountID interface{}) *MockSiaService_DeleteSlabsByAppAccount_Call {
	return &MockSiaService_DeleteSlabsByAppAccount_Call{Call: _e.mock.On("DeleteSlabsByAppAccount", ctx, siaAppAccountID)}
}

func (_c *MockSiaService_DeleteSlabsByAppAccount_Call) Run(run func(ctx context.Context, siaAppAccountID uint)) *MockSiaService_DeleteSlabsByAppAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_DeleteSlabsByAppAccount_Call) Return(_a0 error) *MockSiaService_DeleteSlabsByAppAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_DeleteSlabsByAppAccount_Call) RunAndReturn(run func(context.Context, uint) error) *MockSiaService_DeleteSlabsByAppAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrphanedSlabs provides a mock function with given fields: ctx, siaAppAccountID
func (_m *MockSiaService) FindOrphanedSlabs(ctx context.Context, siaAppAccountID uint) ([]string, error) {
	ret := _m.Called(ctx, siaAppAccountID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrphanedSlabs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]string, error)); ok {
		return rf(ctx, siaAppAccountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []string); ok {
		r0 = rf(ctx, siaAppAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, siaAppAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_FindOrphanedSlabs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrphanedSlabs'
type MockSiaService_FindOrphanedSlabs_Call struct {
	*mock.Call
}

// FindOrphanedSlabs is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
func (_e *MockSiaService_Expecter) FindOrphanedSlabs(ctx interface{}, siaAppAccountID interface{}) *MockSiaService_FindOrphanedSlabs_Call {
	return &MockSiaService_FindOrphanedSlabs_Call{Call: _e.mock.On("FindOrphanedSlabs", ctx, siaAppAccountID)}
}

func (_c *MockSiaService_FindOrphanedSlabs_Call) Run(run func(ctx context.Context, siaAppAccountID uint)) *MockSiaService_FindOrphanedSlabs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_FindOrphanedSlabs_Call) Return(_a0 []string, _a1 error) *MockSiaService_FindOrphanedSlabs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_FindOrphanedSlabs_Call) RunAndReturn(run func(context.Context, uint) ([]string, error)) *MockSiaService_FindOrphanedSlabs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, userID
func (_m *MockSiaService) GetAccount(ctx context.Context, userID uint) (*db.SiaAccount, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *db.SiaAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*db.SiaAccount, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *db.SiaAccount); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SiaAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockSiaService_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSiaService_Expecter) GetAccount(ctx interface{}, userID interface{}) *MockSiaService_GetAccount_Call {
	return &MockSiaService_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, userID)}
}

func (_c *MockSiaService_GetAccount_Call) Run(run func(ctx context.Context, userID uint)) *MockSiaService_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_GetAccount_Call) Return(_a0 *db.SiaAccount, _a1 error) *MockSiaService_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_GetAccount_Call) RunAndReturn(run func(context.Context, uint) (*db.SiaAccount, error)) *MockSiaService_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByID provides a mock function with given fields: ctx, id
func (_m *MockSiaService) GetAccountByID(ctx context.Context, id uint) (*db.SiaAccount, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByID")
	}

	var r0 *db.SiaAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*db.SiaAccount, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *db.SiaAccount); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SiaAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_GetAccountByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByID'
type MockSiaService_GetAccountByID_Call struct {
	*mock.Call
}

// GetAccountByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockSiaService_Expecter) GetAccountByID(ctx interface{}, id interface{}) *MockSiaService_GetAccountByID_Call {
	return &MockSiaService_GetAccountByID_Call{Call: _e.mock.On("GetAccountByID", ctx, id)}
}

func (_c *MockSiaService_GetAccountByID_Call) Run(run func(ctx context.Context, id uint)) *MockSiaService_GetAccountByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_GetAccountByID_Call) Return(_a0 *db.SiaAccount, _a1 error) *MockSiaService_GetAccountByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_GetAccountByID_Call) RunAndReturn(run func(context.Context, uint) (*db.SiaAccount, error)) *MockSiaService_GetAccountByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByQuotaKey provides a mock function with given fields: ctx, quotaKey
func (_m *MockSiaService) GetAccountByQuotaKey(ctx context.Context, quotaKey string) (*db.SiaAccount, error) {
	ret := _m.Called(ctx, quotaKey)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByQuotaKey")
	}

	var r0 *db.SiaAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*db.SiaAccount, error)); ok {
		return rf(ctx, quotaKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *db.SiaAccount); ok {
		r0 = rf(ctx, quotaKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SiaAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, quotaKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_GetAccountByQuotaKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByQuotaKey'
type MockSiaService_GetAccountByQuotaKey_Call struct {
	*mock.Call
}

// GetAccountByQuotaKey is a helper method to define mock.On call
//   - ctx context.Context
//   - quotaKey string
func (_e *MockSiaService_Expecter) GetAccountByQuotaKey(ctx interface{}, quotaKey interface{}) *MockSiaService_GetAccountByQuotaKey_Call {
	return &MockSiaService_GetAccountByQuotaKey_Call{Call: _e.mock.On("GetAccountByQuotaKey", ctx, quotaKey)}
}

func (_c *MockSiaService_GetAccountByQuotaKey_Call) Run(run func(ctx context.Context, quotaKey string)) *MockSiaService_GetAccountByQuotaKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSiaService_GetAccountByQuotaKey_Call) Return(_a0 *db.SiaAccount, _a1 error) *MockSiaService_GetAccountByQuotaKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_GetAccountByQuotaKey_Call) RunAndReturn(run func(context.Context, string) (*db.SiaAccount, error)) *MockSiaService_GetAccountByQuotaKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppAccountByKey provides a mock function with given fields: ctx, accountKey
func (_m *MockSiaService) GetAppAccountByKey(ctx context.Context, accountKey types.PublicKey) (*db.SiaAppAccount, error) {
	ret := _m.Called(ctx, accountKey)

	if len(ret) == 0 {
		panic("no return value specified for GetAppAccountByKey")
	}

	var r0 *db.SiaAppAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.PublicKey) (*db.SiaAppAccount, error)); ok {
		return rf(ctx, accountKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.PublicKey) *db.SiaAppAccount); ok {
		r0 = rf(ctx, accountKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SiaAppAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.PublicKey) error); ok {
		r1 = rf(ctx, accountKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_GetAppAccountByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppAccountByKey'
type MockSiaService_GetAppAccountByKey_Call struct {
	*mock.Call
}

// GetAppAccountByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - accountKey types.PublicKey
func (_e *MockSiaService_Expecter) GetAppAccountByKey(ctx interface{}, accountKey interface{}) *MockSiaService_GetAppAccountByKey_Call {
	return &MockSiaService_GetAppAccountByKey_Call{Call: _e.mock.On("GetAppAccountByKey", ctx, accountKey)}
}

func (_c *MockSiaService_GetAppAccountByKey_Call) Run(run func(ctx context.Context, accountKey types.PublicKey)) *MockSiaService_GetAppAccountByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.PublicKey))
	})
	return _c
}

func (_c *MockSiaService_GetAppAccountByKey_Call) Return(_a0 *db.SiaAppAccount, _a1 error) *MockSiaService_GetAppAccountByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_GetAppAccountByKey_Call) RunAndReturn(run func(context.Context, types.PublicKey) (*db.SiaAppAccount, error)) *MockSiaService_GetAppAccountByKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppsSummary provides a mock function with given fields: ctx, userID
func (_m *MockSiaService) GetAppsSummary(ctx context.Context, userID uint) (*core.AppsSummary, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAppsSummary")
	}

	var r0 *core.AppsSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*core.AppsSummary, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *core.AppsSummary); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.AppsSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_GetAppsSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppsSummary'
type MockSiaService_GetAppsSummary_Call struct {
	*mock.Call
}

// GetAppsSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSiaService_Expecter) GetAppsSummary(ctx interface{}, userID interface{}) *MockSiaService_GetAppsSummary_Call {
	return &MockSiaService_GetAppsSummary_Call{Call: _e.mock.On("GetAppsSummary", ctx, userID)}
}

func (_c *MockSiaService_GetAppsSummary_Call) Run(run func(ctx context.Context, userID uint)) *MockSiaService_GetAppsSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_GetAppsSummary_Call) Return(_a0 *core.AppsSummary, _a1 error) *MockSiaService_GetAppsSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_GetAppsSummary_Call) RunAndReturn(run func(context.Context, uint) (*core.AppsSummary, error)) *MockSiaService_GetAppsSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthRequest provides a mock function with given fields: ctx, requestID
func (_m *MockSiaService) GetAuthRequest(ctx context.Context, requestID string) (*db.AuthRequest, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthRequest")
	}

	var r0 *db.AuthRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*db.AuthRequest, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *db.AuthRequest); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.AuthRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_GetAuthRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthRequest'
type MockSiaService_GetAuthRequest_Call struct {
	*mock.Call
}

// GetAuthRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
func (_e *MockSiaService_Expecter) GetAuthRequest(ctx interface{}, requestID interface{}) *MockSiaService_GetAuthRequest_Call {
	return &MockSiaService_GetAuthRequest_Call{Call: _e.mock.On("GetAuthRequest", ctx, requestID)}
}

func (_c *MockSiaService_GetAuthRequest_Call) Run(run func(ctx context.Context, requestID string)) *MockSiaService_GetAuthRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSiaService_GetAuthRequest_Call) Return(_a0 *db.AuthRequest, _a1 error) *MockSiaService_GetAuthRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_GetAuthRequest_Call) RunAndReturn(run func(context.Context, string) (*db.AuthRequest, error)) *MockSiaService_GetAuthRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetFundingCursor provides a mock function with given fields: ctx
func (_m *MockSiaService) GetFundingCursor(ctx context.Context) (*db.FundingCursor, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFundingCursor")
	}

	var r0 *db.FundingCursor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*db.FundingCursor, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *db.FundingCursor); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.FundingCursor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_GetFundingCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFundingCursor'
type MockSiaService_GetFundingCursor_Call struct {
	*mock.Call
}

// GetFundingCursor is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSiaService_Expecter) GetFundingCursor(ctx interface{}) *MockSiaService_GetFundingCursor_Call {
	return &MockSiaService_GetFundingCursor_Call{Call: _e.mock.On("GetFundingCursor", ctx)}
}

func (_c *MockSiaService_GetFundingCursor_Call) Run(run func(ctx context.Context)) *MockSiaService_GetFundingCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSiaService_GetFundingCursor_Call) Return(_a0 *db.FundingCursor, _a1 error) *MockSiaService_GetFundingCursor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_GetFundingCursor_Call) RunAndReturn(run func(context.Context) (*db.FundingCursor, error)) *MockSiaService_GetFundingCursor_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockSiaService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSiaService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockSiaService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockSiaService_Expecter) ID() *MockSiaService_ID_Call {
	return &MockSiaService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockSiaService_ID_Call) Run(run func()) *MockSiaService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSiaService_ID_Call) Return(_a0 string) *MockSiaService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_ID_Call) RunAndReturn(run func() string) *MockSiaService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppAccounts provides a mock function with given fields: ctx, siaAccountID
func (_m *MockSiaService) ListAppAccounts(ctx context.Context, siaAccountID uint) ([]db.SiaAppAccount, error) {
	ret := _m.Called(ctx, siaAccountID)

	if len(ret) == 0 {
		panic("no return value specified for ListAppAccounts")
	}

	var r0 []db.SiaAppAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]db.SiaAppAccount, error)); ok {
		return rf(ctx, siaAccountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []db.SiaAppAccount); ok {
		r0 = rf(ctx, siaAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SiaAppAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, siaAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_ListAppAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppAccounts'
type MockSiaService_ListAppAccounts_Call struct {
	*mock.Call
}

// ListAppAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAccountID uint
func (_e *MockSiaService_Expecter) ListAppAccounts(ctx interface{}, siaAccountID interface{}) *MockSiaService_ListAppAccounts_Call {
	return &MockSiaService_ListAppAccounts_Call{Call: _e.mock.On("ListAppAccounts", ctx, siaAccountID)}
}

func (_c *MockSiaService_ListAppAccounts_Call) Run(run func(ctx context.Context, siaAccountID uint)) *MockSiaService_ListAppAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_ListAppAccounts_Call) Return(_a0 []db.SiaAppAccount, _a1 error) *MockSiaService_ListAppAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_ListAppAccounts_Call) RunAndReturn(run func(context.Context, uint) ([]db.SiaAppAccount, error)) *MockSiaService_ListAppAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListProvisionedAccounts provides a mock function with given fields: ctx
func (_m *MockSiaService) ListProvisionedAccounts(ctx context.Context) ([]db.SiaAccount, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProvisionedAccounts")
	}

	var r0 []db.SiaAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.SiaAccount, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.SiaAccount); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SiaAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_ListProvisionedAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProvisionedAccounts'
type MockSiaService_ListProvisionedAccounts_Call struct {
	*mock.Call
}

// ListProvisionedAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSiaService_Expecter) ListProvisionedAccounts(ctx interface{}) *MockSiaService_ListProvisionedAccounts_Call {
	return &MockSiaService_ListProvisionedAccounts_Call{Call: _e.mock.On("ListProvisionedAccounts", ctx)}
}

func (_c *MockSiaService_ListProvisionedAccounts_Call) Run(run func(ctx context.Context)) *MockSiaService_ListProvisionedAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSiaService_ListProvisionedAccounts_Call) Return(_a0 []db.SiaAccount, _a1 error) *MockSiaService_ListProvisionedAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_ListProvisionedAccounts_Call) RunAndReturn(run func(context.Context) ([]db.SiaAccount, error)) *MockSiaService_ListProvisionedAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListSlabsByAppAccount provides a mock function with given fields: ctx, siaAppAccountID
func (_m *MockSiaService) ListSlabsByAppAccount(ctx context.Context, siaAppAccountID uint) ([]db.SiaSlab, error) {
	ret := _m.Called(ctx, siaAppAccountID)

	if len(ret) == 0 {
		panic("no return value specified for ListSlabsByAppAccount")
	}

	var r0 []db.SiaSlab
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]db.SiaSlab, error)); ok {
		return rf(ctx, siaAppAccountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []db.SiaSlab); ok {
		r0 = rf(ctx, siaAppAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SiaSlab)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, siaAppAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_ListSlabsByAppAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSlabsByAppAccount'
type MockSiaService_ListSlabsByAppAccount_Call struct {
	*mock.Call
}

// ListSlabsByAppAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
func (_e *MockSiaService_Expecter) ListSlabsByAppAccount(ctx interface{}, siaAppAccountID interface{}) *MockSiaService_ListSlabsByAppAccount_Call {
	return &MockSiaService_ListSlabsByAppAccount_Call{Call: _e.mock.On("ListSlabsByAppAccount", ctx, siaAppAccountID)}
}

func (_c *MockSiaService_ListSlabsByAppAccount_Call) Run(run func(ctx context.Context, siaAppAccountID uint)) *MockSiaService_ListSlabsByAppAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_ListSlabsByAppAccount_Call) Return(_a0 []db.SiaSlab, _a1 error) *MockSiaService_ListSlabsByAppAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_ListSlabsByAppAccount_Call) RunAndReturn(run func(context.Context, uint) ([]db.SiaSlab, error)) *MockSiaService_ListSlabsByAppAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function with no fields
func (_m *MockSiaService) Logger() *portalcore.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *portalcore.Logger
	if rf, ok := ret.Get(0).(func() *portalcore.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portalcore.Logger)
		}
	}

	return r0
}

// MockSiaService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockSiaService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockSiaService_Expecter) Logger() *MockSiaService_Logger_Call {
	return &MockSiaService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockSiaService_Logger_Call) Run(run func()) *MockSiaService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSiaService_Logger_Call) Return(_a0 *portalcore.Logger) *MockSiaService_Logger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_Logger_Call) RunAndReturn(run func() *portalcore.Logger) *MockSiaService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// PruneAccount provides a mock function with given fields: ctx, userID
func (_m *MockSiaService) PruneAccount(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for PruneAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_PruneAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneAccount'
type MockSiaService_PruneAccount_Call struct {
	*mock.Call
}

// PruneAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSiaService_Expecter) PruneAccount(ctx interface{}, userID interface{}) *MockSiaService_PruneAccount_Call {
	return &MockSiaService_PruneAccount_Call{Call: _e.mock.On("PruneAccount", ctx, userID)}
}

func (_c *MockSiaService_PruneAccount_Call) Run(run func(ctx context.Context, userID uint)) *MockSiaService_PruneAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_PruneAccount_Call) Return(_a0 error) *MockSiaService_PruneAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_PruneAccount_Call) RunAndReturn(run func(context.Context, uint) error) *MockSiaService_PruneAccount_Call {
	_c.Call.Return(run)
	return _c
}

// PruneSlabs provides a mock function with given fields: ctx, siaAppAccountID
func (_m *MockSiaService) PruneSlabs(ctx context.Context, siaAppAccountID uint) error {
	ret := _m.Called(ctx, siaAppAccountID)

	if len(ret) == 0 {
		panic("no return value specified for PruneSlabs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, siaAppAccountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_PruneSlabs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneSlabs'
type MockSiaService_PruneSlabs_Call struct {
	*mock.Call
}

// PruneSlabs is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
func (_e *MockSiaService_Expecter) PruneSlabs(ctx interface{}, siaAppAccountID interface{}) *MockSiaService_PruneSlabs_Call {
	return &MockSiaService_PruneSlabs_Call{Call: _e.mock.On("PruneSlabs", ctx, siaAppAccountID)}
}

func (_c *MockSiaService_PruneSlabs_Call) Run(run func(ctx context.Context, siaAppAccountID uint)) *MockSiaService_PruneSlabs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_PruneSlabs_Call) Return(_a0 error) *MockSiaService_PruneSlabs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_PruneSlabs_Call) RunAndReturn(run func(context.Context, uint) error) *MockSiaService_PruneSlabs_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAccount provides a mock function with given fields: ctx, userID
func (_m *MockSiaService) RegisterAccount(ctx context.Context, userID uint) (*db.SiaAccount, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterAccount")
	}

	var r0 *db.SiaAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*db.SiaAccount, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *db.SiaAccount); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SiaAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_RegisterAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAccount'
type MockSiaService_RegisterAccount_Call struct {
	*mock.Call
}

// RegisterAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockSiaService_Expecter) RegisterAccount(ctx interface{}, userID interface{}) *MockSiaService_RegisterAccount_Call {
	return &MockSiaService_RegisterAccount_Call{Call: _e.mock.On("RegisterAccount", ctx, userID)}
}

func (_c *MockSiaService_RegisterAccount_Call) Run(run func(ctx context.Context, userID uint)) *MockSiaService_RegisterAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSiaService_RegisterAccount_Call) Return(_a0 *db.SiaAccount, _a1 error) *MockSiaService_RegisterAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_RegisterAccount_Call) RunAndReturn(run func(context.Context, uint) (*db.SiaAccount, error)) *MockSiaService_RegisterAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAppAccount provides a mock function with given fields: ctx, siaAccountID, accountKey
func (_m *MockSiaService) RegisterAppAccount(ctx context.Context, siaAccountID uint, accountKey types.PublicKey) (*db.SiaAppAccount, error) {
	ret := _m.Called(ctx, siaAccountID, accountKey)

	if len(ret) == 0 {
		panic("no return value specified for RegisterAppAccount")
	}

	var r0 *db.SiaAppAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, types.PublicKey) (*db.SiaAppAccount, error)); ok {
		return rf(ctx, siaAccountID, accountKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, types.PublicKey) *db.SiaAppAccount); ok {
		r0 = rf(ctx, siaAccountID, accountKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SiaAppAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, types.PublicKey) error); ok {
		r1 = rf(ctx, siaAccountID, accountKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSiaService_RegisterAppAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAppAccount'
type MockSiaService_RegisterAppAccount_Call struct {
	*mock.Call
}

// RegisterAppAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAccountID uint
//   - accountKey types.PublicKey
func (_e *MockSiaService_Expecter) RegisterAppAccount(ctx interface{}, siaAccountID interface{}, accountKey interface{}) *MockSiaService_RegisterAppAccount_Call {
	return &MockSiaService_RegisterAppAccount_Call{Call: _e.mock.On("RegisterAppAccount", ctx, siaAccountID, accountKey)}
}

func (_c *MockSiaService_RegisterAppAccount_Call) Run(run func(ctx context.Context, siaAccountID uint, accountKey types.PublicKey)) *MockSiaService_RegisterAppAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(types.PublicKey))
	})
	return _c
}

func (_c *MockSiaService_RegisterAppAccount_Call) Return(_a0 *db.SiaAppAccount, _a1 error) *MockSiaService_RegisterAppAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSiaService_RegisterAppAccount_Call) RunAndReturn(run func(context.Context, uint, types.PublicKey) (*db.SiaAppAccount, error)) *MockSiaService_RegisterAppAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterObject provides a mock function with given fields: ctx, siaAppAccountID, objectID, slabIDs
func (_m *MockSiaService) RegisterObject(ctx context.Context, siaAppAccountID uint, objectID string, slabIDs []string) error {
	ret := _m.Called(ctx, siaAppAccountID, objectID, slabIDs)

	if len(ret) == 0 {
		panic("no return value specified for RegisterObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, []string) error); ok {
		r0 = rf(ctx, siaAppAccountID, objectID, slabIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_RegisterObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterObject'
type MockSiaService_RegisterObject_Call struct {
	*mock.Call
}

// RegisterObject is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
//   - objectID string
//   - slabIDs []string
func (_e *MockSiaService_Expecter) RegisterObject(ctx interface{}, siaAppAccountID interface{}, objectID interface{}, slabIDs interface{}) *MockSiaService_RegisterObject_Call {
	return &MockSiaService_RegisterObject_Call{Call: _e.mock.On("RegisterObject", ctx, siaAppAccountID, objectID, slabIDs)}
}

func (_c *MockSiaService_RegisterObject_Call) Run(run func(ctx context.Context, siaAppAccountID uint, objectID string, slabIDs []string)) *MockSiaService_RegisterObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockSiaService_RegisterObject_Call) Return(_a0 error) *MockSiaService_RegisterObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_RegisterObject_Call) RunAndReturn(run func(context.Context, uint, string, []string) error) *MockSiaService_RegisterObject_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterSlab provides a mock function with given fields: ctx, siaAppAccountID, slabID
func (_m *MockSiaService) RegisterSlab(ctx context.Context, siaAppAccountID uint, slabID string) error {
	ret := _m.Called(ctx, siaAppAccountID, slabID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterSlab")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, siaAppAccountID, slabID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_RegisterSlab_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterSlab'
type MockSiaService_RegisterSlab_Call struct {
	*mock.Call
}

// RegisterSlab is a helper method to define mock.On call
//   - ctx context.Context
//   - siaAppAccountID uint
//   - slabID string
func (_e *MockSiaService_Expecter) RegisterSlab(ctx interface{}, siaAppAccountID interface{}, slabID interface{}) *MockSiaService_RegisterSlab_Call {
	return &MockSiaService_RegisterSlab_Call{Call: _e.mock.On("RegisterSlab", ctx, siaAppAccountID, slabID)}
}

func (_c *MockSiaService_RegisterSlab_Call) Run(run func(ctx context.Context, siaAppAccountID uint, slabID string)) *MockSiaService_RegisterSlab_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockSiaService_RegisterSlab_Call) Return(_a0 error) *MockSiaService_RegisterSlab_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_RegisterSlab_Call) RunAndReturn(run func(context.Context, uint, string) error) *MockSiaService_RegisterSlab_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function with given fields: cfg
func (_m *MockSiaService) SetConfig(cfg config.Manager) {
	_m.Called(cfg)
}

// MockSiaService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockSiaService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockSiaService_Expecter) SetConfig(cfg interface{}) *MockSiaService_SetConfig_Call {
	return &MockSiaService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockSiaService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockSiaService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Manager))
	})
	return _c
}

func (_c *MockSiaService_SetConfig_Call) Return() *MockSiaService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSiaService_SetConfig_Call) RunAndReturn(run func(config.Manager)) *MockSiaService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function with given fields: ctx
func (_m *MockSiaService) SetContext(ctx portalcore.Context) {
	_m.Called(ctx)
}

// MockSiaService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockSiaService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx portalcore.Context
func (_e *MockSiaService_Expecter) SetContext(ctx interface{}) *MockSiaService_SetContext_Call {
	return &MockSiaService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockSiaService_SetContext_Call) Run(run func(ctx portalcore.Context)) *MockSiaService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(portalcore.Context))
	})
	return _c
}

func (_c *MockSiaService_SetContext_Call) Return() *MockSiaService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSiaService_SetContext_Call) RunAndReturn(run func(portalcore.Context)) *MockSiaService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function with given fields: _a0
func (_m *MockSiaService) SetDB(_a0 *gorm.DB) {
	_m.Called(_a0)
}

// MockSiaService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockSiaService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - _a0 *gorm.DB
func (_e *MockSiaService_Expecter) SetDB(_a0 interface{}) *MockSiaService_SetDB_Call {
	return &MockSiaService_SetDB_Call{Call: _e.mock.On("SetDB", _a0)}
}

func (_c *MockSiaService_SetDB_Call) Run(run func(_a0 *gorm.DB)) *MockSiaService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockSiaService_SetDB_Call) Return() *MockSiaService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSiaService_SetDB_Call) RunAndReturn(run func(*gorm.DB)) *MockSiaService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function with given fields: logger
func (_m *MockSiaService) SetLogger(logger *portalcore.Logger) {
	_m.Called(logger)
}

// MockSiaService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockSiaService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *portalcore.Logger
func (_e *MockSiaService_Expecter) SetLogger(logger interface{}) *MockSiaService_SetLogger_Call {
	return &MockSiaService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockSiaService_SetLogger_Call) Run(run func(logger *portalcore.Logger)) *MockSiaService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*portalcore.Logger))
	})
	return _c
}

func (_c *MockSiaService_SetLogger_Call) Return() *MockSiaService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSiaService_SetLogger_Call) RunAndReturn(run func(*portalcore.Logger)) *MockSiaService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// StoreAuthRequest provides a mock function with given fields: ctx, requestID, userID
func (_m *MockSiaService) StoreAuthRequest(ctx context.Context, requestID string, userID uint) error {
	ret := _m.Called(ctx, requestID, userID)

	if len(ret) == 0 {
		panic("no return value specified for StoreAuthRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) error); ok {
		r0 = rf(ctx, requestID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_StoreAuthRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreAuthRequest'
type MockSiaService_StoreAuthRequest_Call struct {
	*mock.Call
}

// StoreAuthRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
//   - userID uint
func (_e *MockSiaService_Expecter) StoreAuthRequest(ctx interface{}, requestID interface{}, userID interface{}) *MockSiaService_StoreAuthRequest_Call {
	return &MockSiaService_StoreAuthRequest_Call{Call: _e.mock.On("StoreAuthRequest", ctx, requestID, userID)}
}

func (_c *MockSiaService_StoreAuthRequest_Call) Run(run func(ctx context.Context, requestID string, userID uint)) *MockSiaService_StoreAuthRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint))
	})
	return _c
}

func (_c *MockSiaService_StoreAuthRequest_Call) Return(_a0 error) *MockSiaService_StoreAuthRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_StoreAuthRequest_Call) RunAndReturn(run func(context.Context, string, uint) error) *MockSiaService_StoreAuthRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFundTargetBytes provides a mock function with given fields: ctx, userID, fundTargetBytes
func (_m *MockSiaService) UpdateFundTargetBytes(ctx context.Context, userID uint, fundTargetBytes uint64) error {
	ret := _m.Called(ctx, userID, fundTargetBytes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFundTargetBytes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint64) error); ok {
		r0 = rf(ctx, userID, fundTargetBytes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_UpdateFundTargetBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFundTargetBytes'
type MockSiaService_UpdateFundTargetBytes_Call struct {
	*mock.Call
}

// UpdateFundTargetBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - fundTargetBytes uint64
func (_e *MockSiaService_Expecter) UpdateFundTargetBytes(ctx interface{}, userID interface{}, fundTargetBytes interface{}) *MockSiaService_UpdateFundTargetBytes_Call {
	return &MockSiaService_UpdateFundTargetBytes_Call{Call: _e.mock.On("UpdateFundTargetBytes", ctx, userID, fundTargetBytes)}
}

func (_c *MockSiaService_UpdateFundTargetBytes_Call) Run(run func(ctx context.Context, userID uint, fundTargetBytes uint64)) *MockSiaService_UpdateFundTargetBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint64))
	})
	return _c
}

func (_c *MockSiaService_UpdateFundTargetBytes_Call) Return(_a0 error) *MockSiaService_UpdateFundTargetBytes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_UpdateFundTargetBytes_Call) RunAndReturn(run func(context.Context, uint, uint64) error) *MockSiaService_UpdateFundTargetBytes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFundingCursor provides a mock function with given fields: ctx, cursor
func (_m *MockSiaService) UpdateFundingCursor(ctx context.Context, cursor *db.FundingCursor) error {
	ret := _m.Called(ctx, cursor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFundingCursor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.FundingCursor) error); ok {
		r0 = rf(ctx, cursor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSiaService_UpdateFundingCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFundingCursor'
type MockSiaService_UpdateFundingCursor_Call struct {
	*mock.Call
}

// UpdateFundingCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - cursor *db.FundingCursor
func (_e *MockSiaService_Expecter) UpdateFundingCursor(ctx interface{}, cursor interface{}) *MockSiaService_UpdateFundingCursor_Call {
	return &MockSiaService_UpdateFundingCursor_Call{Call: _e.mock.On("UpdateFundingCursor", ctx, cursor)}
}

func (_c *MockSiaService_UpdateFundingCursor_Call) Run(run func(ctx context.Context, cursor *db.FundingCursor)) *MockSiaService_UpdateFundingCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.FundingCursor))
	})
	return _c
}

func (_c *MockSiaService_UpdateFundingCursor_Call) Return(_a0 error) *MockSiaService_UpdateFundingCursor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSiaService_UpdateFundingCursor_Call) RunAndReturn(run func(context.Context, *db.FundingCursor) error) *MockSiaService_UpdateFundingCursor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSiaService creates a new instance of MockSiaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSiaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSiaService {
	mock := &MockSiaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
