dir: ./internal/testing/mocks
filename: "Mock{{.InterfaceName}}.go"
outpkg: mocks
packages:
  go.lumeweb.com/portal-plugin-sia/core:
    interfaces:
      SiaService: {}
      QuotaService: {}
      AdminClient: {}
