name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: LumeWeb/workflows/.github/workflows/build-plugin.yml@develop
    with:
      additional_dependencies: 'go.lumeweb.com/portal-plugin-core@develop,go.lumeweb.com/portal-plugin-quota@develop,go.lumeweb.com/portal-plugin-dashboard@develop'
      replacements: 'go.sia.tech/indexd=go.lumeweb.com/indexd@v0.0.0-20260630071444-1576b7f97da5'
    secrets: inherit
